a=input("enter the marks in sub1: ")
b=input("enter the marks in sub2: ")
c=input("enter the marks in sub3: ")
d=input("enter the marks in sub4: ")
e=input("enter the marks in sub5: ")
print("calculating the total marks....")
total=int(a)+int(b)+int(c)+int(d)+int(e)
print("the total marks is ..... ", total)